version: 2
updates:
- package-ecosystem: docker
  directory: "/php7.4-cli"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/php7.3-cli"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: php
    versions:
    - ">= 7.4.a, < 7.5"
- package-ecosystem: docker
  directory: "/php7.1-cli"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: php
    versions:
    - ">= 7.2.a, < 7.5"
- package-ecosystem: docker
  directory: "/jenkins"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
